# Generated by Django 3.1.7 on 2021-04-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_visitor_website_traffic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website_traffic',
        ),
    ]
